# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: ebr.proto
# Protobuf Python Version: 5.29.0
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder

_runtime_version.ValidateProtobufRuntimeVersion(_runtime_version.Domain.PUBLIC, 5, 29, 0, "", "ebr.proto")
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(
    b'\n\tebr.proto\x12\x03\x65\x62r"\'\n\rSearchRequest\x12\x0b\n\x03ids\x18\x01 \x03(\x05\x12\t\n\x01k\x18\x02 \x01(\x05"4\n\x0eSearchResponse\x12"\n\x07results\x18\x01 \x03(\x0b\x32\x11.ebr.SearchResult"<\n\x0cSearchResult\x12\n\n\x02id\x18\x01 \x01(\x05\x12\r\n\x05score\x18\x02 \x01(\x02\x12\x11\n\tsource_id\x18\x03 \x01(\x05\x32\x41\n\nEBRService\x12\x33\n\x06Search\x12\x12.ebr.SearchRequest\x1a\x13.ebr.SearchResponse"\x00\x62\x06proto3'
)

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, "ebr_pb2", _globals)
if not _descriptor._USE_C_DESCRIPTORS:
    DESCRIPTOR._loaded_options = None
    _globals["_SEARCHREQUEST"]._serialized_start = 18
    _globals["_SEARCHREQUEST"]._serialized_end = 57
    _globals["_SEARCHRESPONSE"]._serialized_start = 59
    _globals["_SEARCHRESPONSE"]._serialized_end = 111
    _globals["_SEARCHRESULT"]._serialized_start = 113
    _globals["_SEARCHRESULT"]._serialized_end = 173
    _globals["_EBRSERVICE"]._serialized_start = 175
    _globals["_EBRSERVICE"]._serialized_end = 240
# @@protoc_insertion_point(module_scope)
